"""Add cabinet fields to users table

Revision ID: 9aded8cf9548
Revises: 14fe11bd6e71
Create Date: 2025-07-11 22:12:49.442966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aded8cf9548'
down_revision: Union[str, Sequence[str], None] = '14fe11bd6e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('siret', sa.String(length=14), nullable=True))
    op.add_column('users', sa.Column('siren', sa.String(length=9), nullable=True))
    op.add_column('users', sa.Column('nom_gerant', sa.String(), nullable=True))
    op.add_column('users', sa.Column('adresse_cabinet', sa.String(), nullable=True))
    op.add_column('users', sa.Column('code_postal', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('ville', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telephone_cabinet', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_cabinet', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_cabinet')
    op.drop_column('users', 'telephone_cabinet')
    op.drop_column('users', 'ville')
    op.drop_column('users', 'code_postal')
    op.drop_column('users', 'adresse_cabinet')
    op.drop_column('users', 'nom_gerant')
    op.drop_column('users', 'siren')
    op.drop_column('users', 'siret')
    # ### end Alembic commands ###
